# Generated by Django 5.0.7 on 2024-07-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="token",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
