# Generated by Django 5.0.7 on 2024-07-18 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_password_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
