# Generated by Django 5.0.7 on 2024-08-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="calendly_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
