# Generated by Django 5.0.7 on 2024-08-09 04:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_tutor_calendly_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="courses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("AI", "Intro to AI"),
                        ("DS", "Data Structure and Algorithms"),
                        ("WT", "Web Technologies"),
                        ("MS", "Modelling and Simulations"),
                    ],
                    max_length=2,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
