# Generated by Django 5.0.4 on 2024-08-07 20:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_tutor_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.profile_picture_upload_path,
            ),
        ),
    ]
